name: Build

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Souce (is this a typo?)
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
    - name: Setup Java
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.7
    - name: Build with Maven
      run: mvn -B --no-transfer-progress clean verify 